apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: bigdata-pipeline
data:
  server.properties: |
    broker.id=1
    zookeeper.connect=zookeeper:2181

    listeners=PLAINTEXT://0.0.0.0:9092
    advertised.listeners=PLAINTEXT://kafka-svc:9092
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT
    inter.broker.listener.name=PLAINTEXT

    offsets.topic.replication.factor=1
    transaction.state.log.replication.factor=1
    transaction.state.log.min.isr=1
    group.initial.rebalance.delay.ms=0

    auto.create.topics.enable=true
