apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: bigdata-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: bigdata-pipeline
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]

  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-rolebinding
  namespace: bigdata-pipeline
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: bigdata-pipeline
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
