apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: bigdata-pipeline
  labels:
    app: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: ghcr.io/piiaa01/tracker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: pipeline-config
