# ================================
# Global configuration
# ================================
project:
  name: energy-emission-pipeline
  version: 1.0.0
  environment: local  # could be 'local', 'dev', 'prod'

# ================================
# Kafka settings
# ================================
kafka:
  bootstrap_servers: "kafka:9092"
  topic_training_metrics: "training.metrics"
  group_id: "record-tracker-test"
  replication_factor: 1
  partitions: 1
  auto_offset_reset: "earliest"

# ================================
# File paths
# ================================
paths:
  output_file: "./data/output.jsonl"
  logs: "./logs/app.log"

# ================================
# Training parameters
# ================================
training:
  model_type: "logistic_regression"
  learning_rate: 0.01
  epochs: 10
  batch_size: 32